# Generated by Django 3.2.3 on 2021-05-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merchant_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='lang',
            new_name='lat',
        ),
    ]
