# Generated by Django 3.2.3 on 2021-05-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_usergeolocation'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitem', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('shop', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
