# Generated by Django 3.2.3 on 2021-05-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '__first__'),
        ('orders', '0002_rejectedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedorder',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='rejectedorder',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
