# Generated by Django 3.2.3 on 2021-05-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_usergeolocation'),
        ('orders', '0002_acceptedorderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptedOrderItems',
            new_name='AcceptedOrderItem',
        ),
    ]
