# Generated by Django 3.2.3 on 2021-05-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_usergeolocation'),
        ('orders', '0003_review_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='store',
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.store'),
        ),
    ]
