# Generated by Django 3.2.3 on 2021-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation_Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper_name', models.TextField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
