# Generated by Django 3.2.3 on 2021-05-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_recommendation_engine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation_Engine',
            new_name='Engine',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='shopkeeper_name',
            new_name='shop',
        ),
    ]
