# Generated by Django 3.2.3 on 2021-05-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210522_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engine',
            new_name='Recommendations',
        ),
    ]
